# Generated by Django 5.2 on 2025-04-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Enter a valid email address.', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('application', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('signature', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'db_table': 'Request',
            },
        ),
    ]
