# Generated by Django 5.2 on 2025-04-09 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_of_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
