# Generated by Django 5.2 on 2025-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_request_date_of_request'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
