# Generated by Django 5.2 on 2025-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='signature',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
